import type { EventItem, Offer, Place, Route } from "@/types/models";

const IMG = {
  restaurant: require("@/assets/images/place-restaurant.png"),
  cafe: require("@/assets/images/place-cafe.png"),
  hotel: require("@/assets/images/place-hotel.png"),
  nature: require("@/assets/images/place-nature.png"),
  activity: require("@/assets/images/place-activity.png"),
  hero: require("@/assets/images/hero-harbor.png"),
};

export const IMAGES = IMG;

const today = new Date().toISOString();

export const PLACES: Place[] = [
  {
    id: "p1",
    name: "Hafenblick Restaurant",
    slug: "hafenblick-restaurant",
    type: "Restaurant",
    category: "restaurant",
    description:
      "Direkt am historischen Museumshafen gelegen, serviert das Hafenblick frischen Fisch aus der Nordsee, regionale Friesenklassiker und eine sorgfältig kuratierte Weinkarte. Die Terrasse bietet einen weiten Blick auf die Segelschiffe und den Sonnenuntergang.",
    short_description:
      "Direkt am Hafen mit herrlichem Ausblick und Fischspezialitäten.",
    address: "Am Hafen 4, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6938,
    lng: 7.7958,
    rating: 4.6,
    reviews_count: 352,
    price_level: 2,
    tags: ["fisch", "romantisch", "outdoor", "ausblick"],
    images: [IMG.restaurant, IMG.hero, IMG.nature],
    phone: "+494464123456",
    email: "info@hafenblick-carolinensiel.de",
    website_url: "https://example.com/hafenblick",
    external_booking_url: "https://example.com/hafenblick/reservieren",
    opening_hours: {
      mo: "Geschlossen",
      di: "12:00 – 22:00",
      mi: "12:00 – 22:00",
      do: "12:00 – 22:00",
      fr: "12:00 – 23:00",
      sa: "11:00 – 23:00",
      so: "11:00 – 21:00",
    },
    is_hot: true,
    is_featured: true,
    distance_m: 120,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p2",
    name: "Fischhaus Carolinensiel",
    slug: "fischhaus-carolinensiel",
    type: "Restaurant",
    category: "restaurant",
    description:
      "Traditionelle Küche mit regionalen Fischspezialitäten direkt vom Kutter. Das Fischhaus ist seit 1978 ein fester Bestandteil der Carolinensieler Hafenkultur.",
    short_description:
      "Traditionelle Küche mit regionalen Fischspezialitäten.",
    address: "Mühlenstraße 12, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.694,
    lng: 7.797,
    rating: 4.5,
    reviews_count: 198,
    price_level: 2,
    tags: ["fisch", "tradition", "familie"],
    images: [IMG.restaurant, IMG.nature],
    phone: "+494464234567",
    email: "kontakt@fischhaus-carolinensiel.de",
    website_url: "https://example.com/fischhaus",
    external_booking_url: "https://example.com/fischhaus/reservieren",
    opening_hours: {
      mo: "12:00 – 21:00",
      di: "12:00 – 21:00",
      mi: "Geschlossen",
      do: "12:00 – 21:00",
      fr: "12:00 – 22:00",
      sa: "12:00 – 22:00",
      so: "12:00 – 21:00",
    },
    is_hot: false,
    is_featured: true,
    distance_m: 150,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p3",
    name: "Deichkönig",
    slug: "deichkoenig",
    type: "Restaurant",
    category: "restaurant",
    description:
      "Moderne friesische Küche mit Blick über den Deich. Saisonale Gerichte, ausgewählte Weine und eine elegante, ruhige Atmosphäre.",
    short_description:
      "Moderne Gerichte und eine schöne Terrasse mit Deichblick.",
    address: "Deichstraße 8, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6925,
    lng: 7.798,
    rating: 4.4,
    reviews_count: 276,
    price_level: 3,
    tags: ["modern", "romantisch", "ausblick", "wein"],
    images: [IMG.restaurant, IMG.hero],
    phone: "+494464345678",
    email: "info@deichkoenig.de",
    website_url: "https://example.com/deichkoenig",
    external_booking_url: "https://example.com/deichkoenig/reservieren",
    opening_hours: {
      mo: "Geschlossen",
      di: "17:00 – 22:00",
      mi: "17:00 – 22:00",
      do: "17:00 – 22:00",
      fr: "17:00 – 23:00",
      sa: "12:00 – 23:00",
      so: "12:00 – 21:00",
    },
    is_hot: true,
    is_featured: true,
    distance_m: 200,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p4",
    name: "Restaurant am Yachthafen",
    slug: "restaurant-am-yachthafen",
    type: "Restaurant",
    category: "restaurant",
    description:
      "Mediterrane Küche mit Blick auf die Yachten. Ideal für einen entspannten Abend.",
    short_description: "Mediterrane Küche direkt am Yachthafen.",
    address: "Hafenkai 22, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6948,
    lng: 7.794,
    rating: 4.3,
    reviews_count: 142,
    price_level: 2,
    tags: ["mediterran", "ausblick", "outdoor"],
    images: [IMG.restaurant, IMG.hero],
    phone: "+494464456789",
    website_url: "https://example.com/yachthafen",
    external_booking_url: "https://example.com/yachthafen/reservieren",
    opening_hours: {
      mo: "12:00 – 22:00",
      di: "12:00 – 22:00",
      mi: "12:00 – 22:00",
      do: "12:00 – 22:00",
      fr: "12:00 – 23:00",
      sa: "12:00 – 23:00",
      so: "12:00 – 22:00",
    },
    is_hot: false,
    is_featured: false,
    distance_m: 320,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p5",
    name: "Café am Hafen",
    slug: "cafe-am-hafen",
    type: "Café",
    category: "cafe",
    description:
      "Gemütliches Café mit hausgemachtem Kuchen und Blick auf den Hafen. Beliebt bei Einheimischen und Gästen.",
    short_description:
      "Gemütliches Café mit hausgemachtem Kuchen und Blick auf den Hafen.",
    address: "Am Hafen 1, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6936,
    lng: 7.795,
    rating: 4.8,
    reviews_count: 512,
    price_level: 1,
    tags: ["kaffee", "kuchen", "ausblick", "ruhig"],
    images: [IMG.cafe, IMG.restaurant],
    phone: "+494464567890",
    email: "hallo@cafe-am-hafen.de",
    website_url: "https://example.com/cafe-am-hafen",
    opening_hours: {
      mo: "08:00 – 18:00",
      di: "08:00 – 18:00",
      mi: "08:00 – 18:00",
      do: "08:00 – 18:00",
      fr: "08:00 – 19:00",
      sa: "08:00 – 19:00",
      so: "09:00 – 18:00",
    },
    is_hot: true,
    is_featured: true,
    distance_m: 80,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p6",
    name: "Teestube Tüdelpott",
    slug: "teestube-tuedelpott",
    type: "Café",
    category: "cafe",
    description:
      "Gemütliches Café mit ostfriesischem Tee, hausgemachten Spezialitäten und einer historischen Hafenatmosphäre.",
    short_description: "Gemütliches Café mit ostfriesischem Tee am Hafen.",
    address: "Mühlenstraße 5, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.694,
    lng: 7.7965,
    rating: 4.7,
    reviews_count: 241,
    price_level: 1,
    tags: ["tee", "kuchen", "ruhig", "tradition"],
    images: [IMG.cafe],
    phone: "+494464678901",
    website_url: "https://example.com/tuedelpott",
    opening_hours: {
      mo: "Geschlossen",
      di: "10:00 – 18:00",
      mi: "10:00 – 18:00",
      do: "10:00 – 18:00",
      fr: "10:00 – 18:00",
      sa: "10:00 – 18:00",
      so: "10:00 – 18:00",
    },
    is_hot: true,
    is_featured: false,
    distance_m: 95,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p7",
    name: "Küstenkaffee",
    slug: "kuestenkaffee",
    type: "Café",
    category: "cafe",
    description:
      "Helles modernes Café mit Spezialitätenkaffee, frischen Bagels und veganen Kuchen.",
    short_description: "Modernes Café mit Spezialitätenkaffee.",
    address: "Strandstraße 14, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.692,
    lng: 7.799,
    rating: 4.5,
    reviews_count: 168,
    price_level: 2,
    tags: ["kaffee", "vegan", "modern"],
    images: [IMG.cafe],
    phone: "+494464789012",
    website_url: "https://example.com/kuestenkaffee",
    opening_hours: {
      mo: "08:00 – 16:00",
      di: "08:00 – 16:00",
      mi: "08:00 – 16:00",
      do: "08:00 – 16:00",
      fr: "08:00 – 17:00",
      sa: "08:00 – 17:00",
      so: "Geschlossen",
    },
    is_hot: false,
    is_featured: false,
    distance_m: 220,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p8",
    name: "Hotel Hafenblick",
    slug: "hotel-hafenblick",
    type: "Hotel",
    category: "hotel",
    description:
      "Boutique-Hotel mit eleganten Zimmern, Hafenblick und Wellnessbereich. Ein ruhiger Rückzugsort im Herzen Carolinensiels.",
    short_description: "Boutique-Hotel mit Hafenblick und Wellnessbereich.",
    address: "Am Hafen 10, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.694,
    lng: 7.796,
    rating: 4.6,
    reviews_count: 298,
    price_level: 3,
    tags: ["wellness", "ausblick", "romantisch"],
    images: [IMG.hotel, IMG.hero],
    phone: "+494464890123",
    email: "reservierung@hotel-hafenblick.de",
    website_url: "https://example.com/hotel-hafenblick",
    external_booking_url: "https://example.com/hotel-hafenblick/buchen",
    opening_hours: {
      mo: "00:00 – 24:00",
      di: "00:00 – 24:00",
      mi: "00:00 – 24:00",
      do: "00:00 – 24:00",
      fr: "00:00 – 24:00",
      sa: "00:00 – 24:00",
      so: "00:00 – 24:00",
    },
    is_hot: false,
    is_featured: true,
    distance_m: 130,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p9",
    name: "Pension Nordlicht",
    slug: "pension-nordlicht",
    type: "Pension",
    category: "hotel",
    description:
      "Familiengeführte Pension mit gemütlichen Zimmern und herzlichem Service.",
    short_description: "Familiengeführte Pension mit herzlichem Service.",
    address: "Friesenstraße 18, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6932,
    lng: 7.794,
    rating: 4.3,
    reviews_count: 89,
    price_level: 1,
    tags: ["familie", "ruhig"],
    images: [IMG.hotel],
    phone: "+494464901234",
    email: "info@pension-nordlicht.de",
    website_url: "https://example.com/pension-nordlicht",
    external_booking_url: "https://example.com/pension-nordlicht/buchen",
    opening_hours: {
      mo: "00:00 – 24:00",
      di: "00:00 – 24:00",
      mi: "00:00 – 24:00",
      do: "00:00 – 24:00",
      fr: "00:00 – 24:00",
      sa: "00:00 – 24:00",
      so: "00:00 – 24:00",
    },
    is_hot: false,
    is_featured: false,
    distance_m: 410,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p10",
    name: "Gästehaus Seewind",
    slug: "gaestehaus-seewind",
    type: "Gästehaus",
    category: "hotel",
    description:
      "Ruhiges Gästehaus in Strandnähe. Frühstück mit regionalen Produkten inklusive.",
    short_description: "Ruhiges Gästehaus in Strandnähe.",
    address: "Strandweg 3, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.691,
    lng: 7.792,
    rating: 4.5,
    reviews_count: 156,
    price_level: 2,
    tags: ["strand", "ruhig", "familie"],
    images: [IMG.hotel],
    phone: "+494464012345",
    website_url: "https://example.com/seewind",
    external_booking_url: "https://example.com/seewind/buchen",
    opening_hours: {
      mo: "00:00 – 24:00",
      di: "00:00 – 24:00",
      mi: "00:00 – 24:00",
      do: "00:00 – 24:00",
      fr: "00:00 – 24:00",
      sa: "00:00 – 24:00",
      so: "00:00 – 24:00",
    },
    is_hot: false,
    is_featured: false,
    distance_m: 540,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p11",
    name: "Friesenhof",
    slug: "friesenhof",
    type: "Hotel",
    category: "hotel",
    description:
      "Traditioneller Friesenhof mit modernen Annehmlichkeiten, Garten und kostenlosen Fahrrädern.",
    short_description: "Traditioneller Friesenhof mit Garten und Fahrrädern.",
    address: "Bauernweg 7, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.696,
    lng: 7.793,
    rating: 4.7,
    reviews_count: 213,
    price_level: 2,
    tags: ["tradition", "familie", "fahrrad"],
    images: [IMG.hotel],
    phone: "+494464112233",
    website_url: "https://example.com/friesenhof",
    external_booking_url: "https://example.com/friesenhof/buchen",
    opening_hours: {
      mo: "00:00 – 24:00",
      di: "00:00 – 24:00",
      mi: "00:00 – 24:00",
      do: "00:00 – 24:00",
      fr: "00:00 – 24:00",
      sa: "00:00 – 24:00",
      so: "00:00 – 24:00",
    },
    is_hot: false,
    is_featured: true,
    distance_m: 620,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p12",
    name: "Hafenrundfahrt",
    slug: "hafenrundfahrt",
    type: "Aktivität",
    category: "aktivitaet",
    description:
      "Eine 90-minütige Bootsfahrt durch den historischen Museumshafen mit Blick auf traditionelle Segelschiffe.",
    short_description: "90-minütige Bootsfahrt durch den Museumshafen.",
    address: "Anleger 1, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6945,
    lng: 7.7955,
    rating: 4.6,
    reviews_count: 184,
    price_level: 2,
    tags: ["wasser", "familie", "outdoor"],
    images: [IMG.activity, IMG.hero],
    phone: "+494464223344",
    website_url: "https://example.com/hafenrundfahrt",
    external_booking_url: "https://example.com/hafenrundfahrt/buchen",
    opening_hours: {
      mo: "10:00 – 17:00",
      di: "10:00 – 17:00",
      mi: "10:00 – 17:00",
      do: "10:00 – 17:00",
      fr: "10:00 – 18:00",
      sa: "10:00 – 18:00",
      so: "10:00 – 18:00",
    },
    is_hot: false,
    is_featured: true,
    distance_m: 110,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p13",
    name: "Fahrradtour am Deich",
    slug: "fahrradtour-am-deich",
    type: "Aktivität",
    category: "aktivitaet",
    description:
      "Geführte Fahrradtour entlang des Deiches mit Blick auf das Wattenmeer.",
    short_description: "Geführte Fahrradtour entlang des Deiches.",
    address: "Deichweg 1, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.692,
    lng: 7.79,
    rating: 4.7,
    reviews_count: 92,
    price_level: 2,
    tags: ["fahrrad", "natur", "outdoor"],
    images: [IMG.activity, IMG.nature],
    phone: "+494464334455",
    website_url: "https://example.com/fahrradtour",
    external_booking_url: "https://example.com/fahrradtour/buchen",
    opening_hours: {
      mo: "09:00 – 18:00",
      di: "09:00 – 18:00",
      mi: "09:00 – 18:00",
      do: "09:00 – 18:00",
      fr: "09:00 – 18:00",
      sa: "09:00 – 18:00",
      so: "09:00 – 18:00",
    },
    is_hot: false,
    is_featured: false,
    distance_m: 480,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p14",
    name: "Wattwanderung",
    slug: "wattwanderung",
    type: "Aktivität",
    category: "natur",
    description:
      "Geführte Wattwanderung mit erfahrenen Wattführern. Erleben Sie das UNESCO-Weltnaturerbe Wattenmeer.",
    short_description: "Geführte Wattwanderung im UNESCO-Weltnaturerbe.",
    address: "Strandzugang 3, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6905,
    lng: 7.788,
    rating: 4.9,
    reviews_count: 312,
    price_level: 2,
    tags: ["natur", "outdoor", "familie", "lernen"],
    images: [IMG.nature, IMG.activity],
    phone: "+494464445566",
    website_url: "https://example.com/wattwanderung",
    external_booking_url: "https://example.com/wattwanderung/buchen",
    opening_hours: {
      mo: "Nach Tide",
      di: "Nach Tide",
      mi: "Nach Tide",
      do: "Nach Tide",
      fr: "Nach Tide",
      sa: "Nach Tide",
      so: "Nach Tide",
    },
    is_hot: false,
    is_featured: true,
    distance_m: 760,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p15",
    name: "Historischer Hafenrundgang",
    slug: "historischer-hafenrundgang",
    type: "Aktivität",
    category: "sehenswuerdigkeit",
    description:
      "Ein geführter Spaziergang durch den historischen Museumshafen mit Erläuterungen zur Schifffahrtsgeschichte.",
    short_description: "Geführter Spaziergang durch den Museumshafen.",
    address: "Hafenmuseum, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.6943,
    lng: 7.7958,
    rating: 4.5,
    reviews_count: 124,
    price_level: 1,
    tags: ["geschichte", "lernen", "outdoor"],
    images: [IMG.hero, IMG.activity],
    phone: "+494464556677",
    website_url: "https://example.com/hafenrundgang",
    opening_hours: {
      mo: "11:00 – 16:00",
      di: "11:00 – 16:00",
      mi: "11:00 – 16:00",
      do: "11:00 – 16:00",
      fr: "11:00 – 16:00",
      sa: "11:00 – 17:00",
      so: "11:00 – 17:00",
    },
    is_hot: false,
    is_featured: false,
    distance_m: 140,
    created_at: today,
    updated_at: today,
  },
  {
    id: "p16",
    name: "Strand Carolinensiel",
    slug: "strand-carolinensiel",
    type: "Strand",
    category: "natur",
    description:
      "Ruhiger Sandstrand mit Strandkörben, perfekt für Familien und entspannte Tage am Meer.",
    short_description: "Ruhiger Sandstrand mit Strandkörben.",
    address: "Strandpromenade, 26409 Carolinensiel",
    city: "Carolinensiel",
    lat: 53.689,
    lng: 7.785,
    rating: 4.6,
    reviews_count: 421,
    price_level: 1,
    tags: ["strand", "familie", "outdoor", "ruhig"],
    images: [IMG.nature],
    opening_hours: {
      mo: "00:00 – 24:00",
      di: "00:00 – 24:00",
      mi: "00:00 – 24:00",
      do: "00:00 – 24:00",
      fr: "00:00 – 24:00",
      sa: "00:00 – 24:00",
      so: "00:00 – 24:00",
    },
    is_hot: false,
    is_featured: true,
    distance_m: 890,
    created_at: today,
    updated_at: today,
  },
];

export const ROUTES: Route[] = [
  {
    id: "r1",
    title: "Hafenrundgang",
    description:
      "Ein entspannter Spaziergang durch den historischen Museumshafen mit Stopps an den schönsten Aussichtspunkten.",
    duration: "1,5 Std.",
    difficulty: "Leicht",
    stops: ["p15", "p1", "p5", "p12"],
    images: [IMG.hero],
    tags: ["geschichte", "outdoor"],
  },
  {
    id: "r2",
    title: "Romantischer Abend",
    description:
      "Ein perfekter Abend zu zweit: Sonnenuntergang am Deich, Dinner am Hafen und ein Drink mit Aussicht.",
    duration: "3 Std.",
    difficulty: "Leicht",
    stops: ["p3", "p1", "p8"],
    images: [IMG.hero],
    tags: ["romantisch", "abend"],
  },
  {
    id: "r3",
    title: "Familienroute",
    description:
      "Aktivitäten und Stopps, die Spaß für die ganze Familie bieten — vom Hafen bis zum Strand.",
    duration: "Halber Tag",
    difficulty: "Leicht",
    stops: ["p12", "p5", "p16", "p2"],
    images: [IMG.activity],
    tags: ["familie", "outdoor"],
  },
  {
    id: "r4",
    title: "Regenwetter-Plan",
    description:
      "Die besten Indoor-Stopps, wenn das Wetter mal nicht mitspielt: Tee, Kuchen und Geschichte.",
    duration: "2,5 Std.",
    difficulty: "Leicht",
    stops: ["p6", "p15", "p7"],
    images: [IMG.cafe],
    tags: ["regen", "indoor"],
  },
  {
    id: "r5",
    title: "Foto-Spots",
    description:
      "Die fotogensten Orte Carolinensiels — von den Segelschiffen am Hafen bis zu den Deichen.",
    duration: "2 Std.",
    difficulty: "Leicht",
    stops: ["p15", "p3", "p16"],
    images: [IMG.hero],
    tags: ["foto", "outdoor"],
  },
  {
    id: "r6",
    title: "2-Stunden-Tour",
    description:
      "Eine kompakte Tour für alle, die wenig Zeit haben aber das Beste sehen wollen.",
    duration: "2 Std.",
    difficulty: "Leicht",
    stops: ["p15", "p5", "p1"],
    images: [IMG.hero],
    tags: ["kurz", "outdoor"],
  },
  {
    id: "r7",
    title: "Strand & Natur Route",
    description:
      "Eine entspannte Route entlang des Deiches mit Wattwanderung und Strandbesuch.",
    duration: "Ganzer Tag",
    difficulty: "Mittel",
    stops: ["p13", "p14", "p16"],
    images: [IMG.nature],
    tags: ["natur", "outdoor", "wandern"],
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "e1",
    title: "Carolinensieler Hafenfest",
    description:
      "Das traditionelle Hafenfest mit Live-Musik, Ständen und maritimer Atmosphäre.",
    date: "12. – 14. Juli 2026",
    location: "Museumshafen Carolinensiel",
    image: IMG.hero,
    external_url: "https://example.com/hafenfest",
  },
  {
    id: "e2",
    title: "Wochenmarkt",
    description:
      "Frische regionale Produkte, jeden Samstagmorgen am Marktplatz.",
    date: "Jeden Samstag, 8:00 – 13:00",
    location: "Marktplatz Carolinensiel",
    image: IMG.activity,
    external_url: "https://example.com/wochenmarkt",
  },
  {
    id: "e3",
    title: "Musik am Hafen",
    description:
      "Sommer-Konzertreihe mit Live-Musik direkt am Museumshafen — jeden Donnerstagabend.",
    date: "Jeden Donnerstag im Sommer",
    location: "Museumshafen Carolinensiel",
    image: IMG.restaurant,
    external_url: "https://example.com/musik-am-hafen",
  },
];

export const OFFERS: Offer[] = [
  {
    id: "o1",
    place_id: "p1",
    title: "3-Gänge-Menü zum Sonderpreis",
    description: "Genießen Sie unser saisonales 3-Gänge-Menü für 39 €.",
    valid_until: "30.09.2026",
    external_url: "https://example.com/hafenblick/angebot",
  },
  {
    id: "o2",
    place_id: "p8",
    title: "2 Nächte zum Preis von 1",
    description:
      "Übernachten Sie zwei Nächte und zahlen Sie nur eine — gültig unter der Woche.",
    valid_until: "31.10.2026",
    external_url: "https://example.com/hotel-hafenblick/angebot",
  },
  {
    id: "o3",
    place_id: "p12",
    title: "Familienticket Hafenrundfahrt",
    description: "2 Erwachsene + 2 Kinder ab 35 € — den ganzen Sommer lang.",
    valid_until: "30.09.2026",
    external_url: "https://example.com/hafenrundfahrt/familie",
  },
];

export function getPlaceById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}

export function getRouteById(id: string): Route | undefined {
  return ROUTES.find((r) => r.id === id);
}

export function getHotPlaces(): Place[] {
  return PLACES.filter((p) => p.is_hot);
}

export function getFeaturedPlaces(): Place[] {
  return PLACES.filter((p) => p.is_featured);
}

export function getPlacesByCategory(cat: string): Place[] {
  if (cat === "all") return PLACES;
  return PLACES.filter((p) => p.category === cat);
}
